Set version for halcyon-font
It looks like a version must be set for yarn to install halcyon-font. This change fixes the following error I was seeing:

yarn install v0.23.3
[1/5] Resolving packages...
error Package "halcyon-font@" doesn't have a "version".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'web' failed to build: The command '/bin/sh -c mkdir -p /halcyon/storage /halcyon/bootstrap/cache  && chmod -R 770 /halcyon/storage /halcyon/bootstrap/cache  && chmod +x /usr/local/bin/composer; sync  && composer install --no-progress  && yarn --pure-lockfile  && yarn cache clean' returned a non-zero code: 1