Remove reference to deleted 'factories' folder
Fixes the following error I was getting following the install guide:

Generating optimized autoload files

                                                                                                          
  [RuntimeException]                                                                                      
  Could not scan for classes inside "database/factories" which does not appear to be a file nor a folder  
                                                                                                          

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: Service 'web' failed to build: The command '/bin/sh -c mkdir -p /halcyon/storage /halcyon/bootstrap/cache  && chmod -R 770 /halcyon/storage /halcyon/bootstrap/cache  && chmod +x /usr/local/bin/composer; sync  && composer install --no-progress  && yarn --pure-lockfile  && yarn cache clean' returned a non-zero code: 1